on:
    push:
        branches:
            - ja

name: CD

jobs:
    deploy:
        name: Deploy

        runs-on: ubuntu-latest

        if: "!contains(github.event.head_commit.message, 'auto rebuilding site')"

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Set up Python 3.7"
                uses: actions/setup-python@v1
                with:
                    python-version: '3.7' # Semantic version range syntax or exact version of a Python version

            -   name: "Display Python version"
                run: python -c "import sys; print(sys.version)"

            -   name: "Install Sphinx dependencies"
                run: sudo apt-get install python-dev build-essential

            -   name: "Cache pip"
                uses: actions/cache@v2
                with:
                    path: ~/.cache/pip
                    key: ${{ runner.os }}-pip-${{ hashFiles('_build/.requirements.txt') }}
                    restore-keys: |
                        ${{ runner.os }}-pip-

            -   name: "Install Sphinx + requirements via pip"
                run: pip install -r _build/.requirements.txt

            -   name: "Build documentation"
                run: make -C _build SPHINXOPTS="-nqW -j auto" html

            -   name: "Deploy GitHub Pages"
                uses: peaceiris/actions-gh-pages@v3
                with:
                    deploy_key: ${{ secrets.MY_ACTIONS_DEPLOY_KEY }}
                    publish_dir: ./_build/html
